### ISSUE TITLE
whats the pytorch version

### ISSUE THREAD

**Issue by ReverseSystem001** [we0091234/Chinese_license_plate_detection_recognition#14]
when i  export_torchscipt. It reports
local/lib/python3.6/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
 can you tell me your training pytroch version?   and have you trained yolov5s. if so, can you public the model. thanks

**Comment by we0091234** [comment]
> when i export_torchscipt. It reports local/lib/python3.6/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.) return torch.floor_divide(self, other) can you tell me your training pytroch version? and have you trained yolov5s. if so, can you public the model. thanks

torch 1.7.1+cu110

**Comment by ReverseSystem001** [comment]
thanks. have you trained the yolov5s?

**Comment by we0091234** [comment]
> thanks. have you trained the yolov5s?
no i haven't，you can train by yourself
