### ISSUE TITLE
label问题

### ISSUE THREAD

**Issue by Manurios-L** [we0091234/Chinese_license_plate_detection_recognition#31]
label x y w h pt1x pt1y pt2x pt2y pt3x pt3y pt4x pt4y
您好我看这个项目的label是这个格式的，我想问一下如果我用的是labelimg的标注工具，只提供label x y w h，这五个值，是否可以训练，运行train.py文件？？？急急急

**Comment by we0091234** [comment]
不可以，这个是关键点的
