### ISSUE TITLE
车牌检测训练问题

### ISSUE THREAD

**Issue by MKTroller** [we0091234/Chinese_license_plate_detection_recognition#32]
您好！我按照您在https://github.com/we0091234/Chinese_license_plate_detection_recognition/tree/main/readme所列的步骤中训练自己模型时，发现出现错误WARN:0@4.775] global loadsave.cpp:248 cv:[ WARN:0@1.605] global loadsave.cpp:248 cv::findDecoder imread_('/mnt/Gpan/Mydata/pytorchPorject/datasets/cc[::findDecoder imread_('/mnt/Gpan/Mydata/pytorchPorject/datasets/ccpd/train_car_plate/train_detect/CCPD/00336805555555-Traceback (most recent call last):
我估计应该是路径设置的问题，但我实在是找不到这个是在哪里改的了，特此想请教一下您！万分感谢！

**Comment by we0091234** [comment]
删了cache文件
